from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives import serialization
import os

def generate_hospital_keys(hospital_name):
    """
    Generates a private and public RSA key pair for a hospital to digitally sign zero-watermarks.
    This replaces the weak XOR 'seed' vulnerability with military-grade asymmetric cryptography.
    """
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
    )
    public_key = private_key.public_key()
    
    # Save keys in a secure directory
    key_dir = os.path.join(os.path.dirname(__file__), 'keys')
    os.makedirs(key_dir, exist_ok=True)
    
    safe_name = hospital_name.replace(' ', '_').replace("'", "").lower()
    priv_path = os.path.join(key_dir, f"{safe_name}_private.pem")
    pub_path = os.path.join(key_dir, f"{safe_name}_public.pem")
    
    with open(priv_path, "wb") as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption()
        ))
        
    with open(pub_path, "wb") as f:
        f.write(public_key.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ))
    return priv_path, pub_path

def sign_zero_watermark(private_key_path, watermark_signature):
    """
    Cryptographically signs the zero watermark using the hospital's private RSA key.
    """
    with open(private_key_path, "rb") as key_file:
        private_key = serialization.load_pem_private_key(
            key_file.read(),
            password=None,
        )
        
    signature = private_key.sign(
        watermark_signature.encode('utf-8'),
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )
    return signature.hex()

def verify_zero_watermark_rsa(public_key_path, watermark_signature, encrypted_hex_signature):
    """
    Cryptographically verifies that the zero-watermark was generated by the hospital possessing the private key.
    """
    try:
        with open(public_key_path, "rb") as key_file:
            public_key = serialization.load_pem_public_key(key_file.read())
            
        public_key.verify(
            bytes.fromhex(encrypted_hex_signature),
            watermark_signature.encode('utf-8'),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        return True # Authentic! Signature matches.
    except Exception as e:
        print(f"RSA Verification Failed: {str(e)}")
        return False # Forgery Detected.
